### ISSUE TITLE
Import by URL stripping slashes after schema

### ISSUE THREAD

**Issue by mwexcell** [vabene1111/recipes#145]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.10.0 - from docker hub

### Bug description
When I import by url, the second slash after the schema gets stripped - so https://a.b.co becomes https:/a.b.co

This causes the url connection to fail because it doesn't think it has a host:

From the debug logs:

Internal Server Error: /recipes/api/recipe-from-url/https:/www.allrecipes.com/recipe/49552/quinoa-and-black-beans/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/recipes/cookbook/views/api.py", line 348, in recipe_from_url
    response = requests.get(url, headers=headers)
  File "/opt/recipes/venv/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/opt/recipes/venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/opt/recipes/venv/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/requests/models.py", line 391, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'https:/www.allrecipes.com/recipe/49552/quinoa-and-black-beans': No host supplied
172.17.0.1 - - [31/Jul/2020:15:27:41 +0000] "GET /recipes/api/recipe-from-url/https:/www.allrecipes.com/recipe/49552/quinoa-and-black-beans/ HTTP/1.1" 500 19704 "https://<personal server removed>/recipes/data/import/url" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"

**Comment by vabene1111** [comment]
Sry for the late answer, since this is not happening for everyone can you please provide some additional information about the browser/setup you are running ?

Is it possible that you have some kind of proxy/firewall/router config that might change the GET parameters passed to your server ? We had problems with this before and i definitly need to fix this (by making it a post request) but for the moment i think that this is your problem.

**Comment by mwexcell** [comment]
I'm on Chrome Version 83.0.4103.106 (Official Build) (64-bit) on Ubuntu 18.04.4 LTS. (I can also recreate it with the same error message/trace on Firefox 77.0.1) The server is a Docker container using the an unmodified image from DockerHub. There is no proxy and no anti-virus etc. in the middle that may modify the URL. The firewall is a packet-filter with all outgoing enabled and no proxy capabilities at the protocol level. Further, all this traffic is local between the two machines so the firewall doesn't even really come into play here. What else can I check?

**Comment by vabene1111** [comment]
that is very interesting. Instead of debugging this for hours, as someone else already had problems with this, i moved the parameter to be a post instead of a get parameter. Didn't really ever make sense the way it was before so now its fixed. 

I hope to get the update out in the next few days, if you have any problems afterwards let me know.

**Comment by vabene1111** [comment]
update is released
