### ISSUE TITLE
add docker secrets support to the images

### ISSUE THREAD

**Issue by Akruidenberg** [vabene1111/recipes#157]
I would like to use docker secrets with docker compose. But the current docker image wont' do this (access denied because password wont read. Please add support support for his for better security

**Comment by vabene1111** [comment]
i have no idea why you get access denied errors and i dont use docker secrets but from what i gather from the documentation you can simply point environment variables to docker secrets. So you would only have to change the docker-compose file to contain the variables from the .env file and point them to the various secrets you want to load.

This is what i found in the [documentation](https://docs.docker.com/engine/swarm/secrets/#:~:text=Note%3A%20Docker%20secrets%20do%20not,if%20you%20use%20%2D%2Dlink%20)
```
 docker service create \
     --name mysql \
     --replicas 1 \
     --network mysql_private \
     --mount type=volume,source=mydata,destination=/var/lib/mysql \
     --secret source=mysql_root_password,target=mysql_root_password \
     --secret source=mysql_password,target=mysql_password \
     -e MYSQL_ROOT_PASSWORD_FILE="/run/secrets/mysql_root_password" \
     -e MYSQL_PASSWORD_FILE="/run/secrets/mysql_password" \
     -e MYSQL_USER="wordpress" \
     -e MYSQL_DATABASE="wordpress" \
     mysql:latest
```

if i need to change something with the image let me know what exactly that would be because i dont see what needs to be changed there.

**Comment by Akruidenberg** [comment]
I would like to use it like this:

```
  recipes:
    image: vabene1111/recipes 
    container_name: recipes
    restart: unless-stopped
    hostname: recipes
    user: $PUID
    networks:
      - reverseproxy
      - intern
    security_opt:
      - no-new-privileges:true       
    volumes:
      - $USERDIR/recipes/staticfiles:/opt/recipes/staticfiles
      - $USERDIR/recipes/mediafiles:/opt/recipes/mediafiles    
    secrets:
      - recipe_secret
      - recipe_postgres
    depends_on:
      - recipes-postgres
      - nginx-recipes
    environment:
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      POSTGRES_HOST: recipes-postgres
      POSTGRES_PORT: 5432 
      POSTGRES_PASSWORD_FILE: /run/secrets/recipe_postgres
      POSTGRES_USER: recipes
      POSTGRES_DB: recipes         
      SECRET_KEY_FILE: /run/secret/recipe_secret
      REVERSE_PROXY_AUTH: 1
      COMMENT_PREF_DEFAULT: 1
      GUNICORN_MEDIA: 0
      ALLOWED_HOSTS: "*"
      COMMENT_PREF_DEFAULT: 1
      MEDIA_URL: /media/
      STATIC_URL: /static/
      SHOPPING_MIN_AUTOSYNC_INTERVAL: 5
      DEBUG: 0
    ## watchtower      
      com.centurylinklabs.watchtower.enable: "true"    
secrets:
  recipe_postgres:
    file: $SECRETSDIR/recipe_postgres  
  recipe_secret:
    file: $SECRETSDIR/recipe_secret
```

**Comment by vabene1111** [comment]
but what do i need to change in the image to allow this ?
I currently dont have the time to figure this out so please let me know of any concrete changes i need to make because right now it looks like you should be able to do exactly what you post without me having to make any changes

**Comment by Akruidenberg** [comment]
I dont know how to fix this myself. The following error is shown:

`Updating database,
Traceback (most recent call last):,
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection,
    self.connect(),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
    return func(*args, **kwargs),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect,
    self.connection = self.get_new_connection(conn_params),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
    return func(*args, **kwargs),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection,
    connection = Database.connect(**conn_params),
  File "/opt/recipes/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect,
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync),
psycopg2.OperationalError: fe_sendauth: no password supplied,
,
,
The above exception was the direct cause of the following exception:,
,
Traceback (most recent call last):,
  File "manage.py", line 15, in <module>,
    execute_from_command_line(sys.argv),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line,
    utility.execute(),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute,
    self.fetch_command(subcommand).run_from_argv(self.argv),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv,
    self.execute(*args, **cmd_options),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute,
    output = self.handle(*args, **options),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped,
    res = handle_func(*args, **kwargs),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 92, in handle,
    executor = MigrationExecutor(connection, self.migration_progress_callback),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__,
    self.loader = MigrationLoader(self.connection),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__,
    self.build_graph(),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 216, in build_graph,
    self.applied_migrations = recorder.applied_migrations(),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations,
    if self.has_table():,
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table,
    with self.connection.cursor() as cursor:,
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
    return func(*args, **kwargs),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor,
    return self._cursor(),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor,
    self.ensure_connection(),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
    return func(*args, **kwargs),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection,
    self.connect(),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__,
    raise dj_exc_value.with_traceback(traceback) from exc_value,
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection,
    self.connect(),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
    return func(*args, **kwargs),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect,
    self.connection = self.get_new_connection(conn_params),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner,
    return func(*args, **kwargs),
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection,
    connection = Database.connect(**conn_params),
  File "/opt/recipes/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect,
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync),
django.db.utils.OperationalError: fe_sendauth: no password supplied,
,
,
0 static files copied to '/opt/recipes/staticfiles', 675 unmodified, 1300 post-processed.,
Done,
[2020-11-06 15:17:02 +0000] [1] [INFO] Starting gunicorn 20.0.4,
[2020-11-06 15:17:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1),
[2020-11-06 15:17:02 +0000] [1] [INFO] Using worker: sync,
[2020-11-06 15:17:02 +0000] [13] [INFO] Booting worker with pid: 13,
192.168.80.28 - - [06/Nov/2020:15:17:27 +0000] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0",`

**Comment by vabene1111** [comment]
it looks like you are using `POSTGRES_PASSWORD_FILE` which is not recognized by django thus django does not get a DB password. You will need to set `POSTGRES_PASSWORD` to a password. Maybe there is a way for django to read password files but i dont know how atm, if anyone wants to they can open a PR to fix this.

i dont really know how docker secrets works and currently dont have the time to investigate this further. Please use one of the offically supported methods if you want me to be able to help you.
