### ISSUE TITLE
I'm getting a module not found error after own build

### ISSUE THREAD

**Issue by ginnyTheCat** [vabene1111/recipes#18]
After my own build I'm always getting this error on start. I don't know much about python modules.
Thank you in advance

The error logs:
```
recipes    | [2020-01-14 14:30:21 +0000] [1] [INFO] Starting gunicorn 19.7.1
recipes    | [2020-01-14 14:30:21 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
recipes    | [2020-01-14 14:30:21 +0000] [1] [INFO] Using worker: sync
recipes    | [2020-01-14 14:30:21 +0000] [8] [INFO] Booting worker with pid: 8
recipes    | [2020-01-14 14:30:21 +0000] [8] [ERROR] Exception in worker process
recipes    | Traceback (most recent call last):
recipes    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
recipes    |     worker.init_process()
recipes    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 126, in init_process
recipes    |     self.load_wsgi()
recipes    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
recipes    |     self.wsgi = self.app.wsgi()
recipes    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
recipes    |     self.callable = self.load()
recipes    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
recipes    |     return self.load_wsgiapp()
recipes    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
recipes    |     return util.import_app(self.app_uri)
recipes    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 352, in import_app
recipes    |     __import__(module)
recipes    | ModuleNotFoundError: No module named 'recipes'
recipes    | [2020-01-14 14:30:22 +0000] [8] [INFO] Worker exiting (pid: 8)
recipes    | [2020-01-14 14:30:22 +0000] [1] [INFO] Shutting down: Master
recipes    | [2020-01-14 14:30:22 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by vabene1111** [comment]
gunicorn cant find the main recipes module (which is basically this apllication). Can you describe how you setup the application ?

**Comment by ginnyTheCat** [comment]
My filestructure:
```
docker-compose.yml
.env (copy of recipes/.env.template)
recipes (cloned repo from GitHub)```

The docker-compose.yml:
```
version: '3'
services:
  recipes:
    image: recipes
    container_name: recipes
    restart: always
    command: "gunicorn --bind 0.0.0.0:8080 recipes.wsgi"
    env_file:
      - ./.env
    volumes:
      - ~/data/recipes:/Recipes
    networks:
      - nginx
      - postgres
networks:
  postgres:
    external:
      name: postgres
  nginx:
    external:
      name: nginx```

I built the image using `docker build recipes/ -t recipes`

**Comment by vabene1111** [comment]
Hmm i actually dont know now if this works the way you did it. I always leave the docker-compose.yml and the .env file inside the recipes folder and start it with 
`docker-compose up -d --build`. You can try different ways but i wont be able to help you there ...
