### ISSUE TITLE
Error 500: There was an error loading a resource!

### ISSUE THREAD

**Issue by dekiesel** [vabene1111/recipes#239]
### Version
Version: 0.11.1

### Bug description
When using the search in "Shopping List" I get

`There was an error loading a resource! <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>`

every time I type a letter in the search box.

That doesn't happen using the search function in "Meal Plan".

Log from docker-compose:

```
nginx_recipes_1  | 10.253.3.5 - - [25/Nov/2020:12:32:01 +0000] "GET /api/recipe/?limit=5&internal=true&query=kol HTTP/1.1" 500 145 "http://192.168.178.11:680/shopping/" "Mozilla/5.0 (Windows NT 10.0; Win64; x
64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36 OPR/72.0.3815.320" "-"
web_recipes_1    | 172.21.0.3 - - [25/Nov/2020:12:32:01 +0000] "GET /api/recipe/?limit=5&internal=true&query=kol HTTP/1.0" 500 145 "http://192.168.178.11:680/shopping/" "Mozilla/5.0 (Windows NT 10.0; Win64; x
64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36 OPR/72.0.3815.320"
```

**Comment by dekiesel** [comment]
Here is a logfile with debug enabled:

```
web_recipes_1    | Internal Server Error: /api/recipe/
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_recipes_1    |     response = get_response(request)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
web_recipes_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_recipes_1    |     return view_func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
web_recipes_1    |     return self.dispatch(request, *args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
web_recipes_1    |     response = self.handle_exception(exc)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
web_recipes_1    |     self.raise_uncaught_exception(exc)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
web_recipes_1    |     raise exc
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
web_recipes_1    |     response = handler(request, *args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
web_recipes_1    |     queryset = self.filter_queryset(self.get_queryset())
web_recipes_1    |   File "/opt/recipes/cookbook/views/api.py", line 212, in get_queryset
web_recipes_1    |     queryset = queryset.filter(internal=True)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
web_recipes_1    |     return self._filter_or_exclude(False, *args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 954, in _filter_or_exclude
web_recipes_1    |     assert not self.query.is_sliced, \
web_recipes_1    | AssertionError: Cannot filter a query once a slice has been taken.
web_recipes_1    | 172.21.0.3 - - [25/Nov/2020:12:38:26 +0000] "GET /api/recipe/?limit=5&internal=true&query=k HTTP/1.0" 500 92271 "http://192.168.178.11:680/shopping/" "Mozilla/5.0 (Windows NT 10.0; Win64; x
64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36 OPR/72.0.3815.320"

```

**Comment by vabene1111** [comment]
this is fixed but i have forgotten to release it .. will do that ASAP, hopefully tomorrow

**Comment by dekiesel** [comment]
No stress, thank you for this amazing piece of software!

**Comment by dekiesel** [comment]
Is this fixed in the dev-branch? If so I could build my own container. My better half has been asking for this feature.

**Comment by vabene1111** [comment]
ah screw it, sry very busy atm, forgot it again ...

released the update now, should be in docker hub (in all build variants) in half an hour or so
