### ISSUE TITLE
Server Error 500 when i start with docker-compose file. 

### ISSUE THREAD

**Issue by cschoeni** [vabene1111/recipes#357]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: actual Version

### Bug description
In my Folder a add a .env File and a docker-compose.yaml with your template. But wenn i start this i become a Server 500 Error. 

```bash
Creating network "recipes_default" with the default driver
Creating recipes_db_recipes_1 ... done
Creating recipes_web_recipes_1 ... done
Creating recipes_nginx_recipes_1 ... done
Attaching to recipes_db_recipes_1, recipes_web_recipes_1, recipes_nginx_recipes_1
db_recipes_1     | The files belonging to this database system will be owned by user "postgres".
db_recipes_1     | This user must also own the server process.
db_recipes_1     | 
db_recipes_1     | The database cluster will be initialized with locale "en_US.utf8".
db_recipes_1     | The default database encoding has accordingly been set to "UTF8".
db_recipes_1     | The default text search configuration will be set to "english".
db_recipes_1     | 
db_recipes_1     | Data page checksums are disabled.
db_recipes_1     |
db_recipes_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_recipes_1     | creating subdirectories ... ok
db_recipes_1     | selecting default max_connections ... 100
db_recipes_1     | selecting default shared_buffers ... 128MB
db_recipes_1     | selecting default timezone ... UTC
db_recipes_1     | selecting dynamic shared memory implementation ... posix
db_recipes_1     | creating configuration files ... ok
nginx_recipes_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_recipes_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_recipes_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_recipes_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
web_recipes_1    | Updating database
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_recipes_1    |     self.connect()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
web_recipes_1    |     self.connection = self.get_new_connection(conn_params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
web_recipes_1    |     connection = Database.connect(**conn_params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
web_recipes_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_recipes_1    | psycopg2.OperationalError: could not connect to server: Connection refused
web_recipes_1    |      Is the server running on host "db_recipes" (172.24.0.2) and accepting
web_recipes_1    |      TCP/IP connections on port 5432?
web_recipes_1    |
web_recipes_1    |
web_recipes_1    | The above exception was the direct cause of the following exception:
web_recipes_1    |
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "manage.py", line 15, in <module>
web_recipes_1    |     execute_from_command_line(sys.argv)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
web_recipes_1    |     utility.execute()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
web_recipes_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
web_recipes_1    |     self.execute(*args, **cmd_options)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
web_recipes_1    |     output = self.handle(*args, **options)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
web_recipes_1    |     res = handle_func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 92, in handle
web_recipes_1    |     executor = MigrationExecutor(connection, self.migration_progress_callback)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_recipes_1    |     self.loader = MigrationLoader(self.connection)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
web_recipes_1    |     self.build_graph()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 216, in build_graph
web_recipes_1    |     self.applied_migrations = recorder.applied_migrations()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
web_recipes_1    |     if self.has_table():
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
web_recipes_1    |     with self.connection.cursor() as cursor:
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
web_recipes_1    |     return self._cursor()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
web_recipes_1    |     self.ensure_connection()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_recipes_1    |     self.connect()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_recipes_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_recipes_1    |     self.connect()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
web_recipes_1    |     self.connection = self.get_new_connection(conn_params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
web_recipes_1    |     return func(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
web_recipes_1    |     connection = Database.connect(**conn_params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
web_recipes_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_recipes_1    | django.db.utils.OperationalError: could not connect to server: Connection refused
web_recipes_1    |      Is the server running on host "db_recipes" (172.24.0.2) and accepting
web_recipes_1    |      TCP/IP connections on port 5432?
web_recipes_1    |
db_recipes_1     | running bootstrap script ... ok
db_recipes_1     | performing post-bootstrap initialization ... sh: locale: not found
db_recipes_1     | 2021-01-27 09:53:02.007 UTC [31] WARNING:  no usable system locales were found
web_recipes_1    | 
web_recipes_1    | 0 static files copied to '/opt/recipes/staticfiles', 507 unmodified, 963 post-processed.
web_recipes_1    | Done
web_recipes_1    | [2021-01-27 09:53:04 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_recipes_1    | [2021-01-27 09:53:04 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
web_recipes_1    | [2021-01-27 09:53:04 +0000] [1] [INFO] Using worker: sync
web_recipes_1    | [2021-01-27 09:53:04 +0000] [14] [INFO] Booting worker with pid: 14
db_recipes_1     | ok
db_recipes_1     | syncing data to disk ... ok
db_recipes_1     |
db_recipes_1     | Success. You can now start the database server using:
db_recipes_1     |
db_recipes_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_recipes_1     | 
db_recipes_1     |
db_recipes_1     | WARNING: enabling "trust" authentication for local connections
db_recipes_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_recipes_1     | --auth-local and --auth-host, the next time you run initdb.
db_recipes_1     | waiting for server to start....2021-01-27 09:53:15.791 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_recipes_1     | 2021-01-27 09:53:15.927 UTC [37] LOG:  database system was shut down at 2021-01-27 09:53:11 UTC
db_recipes_1     | 2021-01-27 09:53:15.975 UTC [36] LOG:  database system is ready to accept connections
db_recipes_1     |  done
db_recipes_1     | server started
db_recipes_1     | CREATE DATABASE
db_recipes_1     |
db_recipes_1     |
db_recipes_1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_recipes_1     |
db_recipes_1     | waiting for server to shut down...2021-01-27 09:53:19.804 UTC [36] LOG:  received fast shutdown request
db_recipes_1     | 2021-01-27 09:53:19.808 UTC [36] LOG:  aborting any active transactions
db_recipes_1     | 2021-01-27 09:53:19.809 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
db_recipes_1     | 2021-01-27 09:53:19.809 UTC [38] LOG:  shutting down
db_recipes_1     | .2021-01-27 09:53:19.943 UTC [36] LOG:  database system is shut down
db_recipes_1     |  done
db_recipes_1     | server stopped
db_recipes_1     |
db_recipes_1     | PostgreSQL init process complete; ready for start up.
db_recipes_1     |
db_recipes_1     | 2021-01-27 09:53:20.071 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_recipes_1     | 2021-01-27 09:53:20.071 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_recipes_1     | 2021-01-27 09:53:20.093 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_recipes_1     | 2021-01-27 09:53:20.179 UTC [50] LOG:  database system was shut down at 2021-01-27 09:53:19 UTC
db_recipes_1     | 2021-01-27 09:53:20.225 UTC [1] LOG:  database system is ready to accept connections
db_recipes_1     | 2021-01-27 09:53:20.788 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.788 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:20.693944+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
db_recipes_1     | 2021-01-27 09:53:20.820 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.820 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:20.819880+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
db_recipes_1     | 2021-01-27 09:53:20.822 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.822 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:20.821336+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
db_recipes_1     | 2021-01-27 09:53:20.830 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.830 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" LIMIT 21
db_recipes_1     | 2021-01-27 09:53:20.833 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.833 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:20.693944+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
db_recipes_1     | 2021-01-27 09:53:20.834 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.834 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:20.693944+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
db_recipes_1     | 2021-01-27 09:53:20.836 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.836 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:20.693944+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
db_recipes_1     | 2021-01-27 09:53:20.837 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.837 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:20.693944+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
db_recipes_1     | 2021-01-27 09:53:20.840 UTC [57] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:20.840 UTC [57] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:20.839078+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
web_recipes_1    | 172.24.0.4 - - [27/Jan/2021:09:53:20 +0000] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36"
nginx_recipes_1  | 172.24.0.1 - - [27/Jan/2021:09:53:20 +0000] "GET / HTTP/1.1" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36" "-"
db_recipes_1     | 2021-01-27 09:53:21.389 UTC [58] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:21.389 UTC [58] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:21.351980+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
db_recipes_1     | 2021-01-27 09:53:21.397 UTC [58] ERROR:  relation "django_session" does not exist at character 109
db_recipes_1     | 2021-01-27 09:53:21.397 UTC [58] STATEMENT:  SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2021-01-27T09:53:21.396796+00:00'::timestamptz AND "django_session"."session_key" = '46i5fxzxazj2t1783ssbkapby7nlh7qv') LIMIT 21
nginx_recipes_1  | 172.24.0.1 - - [27/Jan/2021:09:53:21 +0000] "GET /favicon.ico HTTP/1.1" 500 145 "http://127.0.0.1/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36" "-"
web_recipes_1    | 172.24.0.4 - - [27/Jan/2021:09:53:21 +0000] "GET /favicon.ico HTTP/1.0" 500 145 "http://127.0.0.1/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36"
```

**Comment by vabene1111** [comment]
the error means that your application is not able to connect to the postgresql databse. Did you set a password in the .env file ?

**Comment by cschoeni** [comment]
Yes i set a password in the .env file. I work on a windows. Its posible, that not work because my windows?

**Comment by cesarblancg** [comment]
The database works well because, at the end of the log, the web_recipes is communicating with the db. It seems like your web_recipes is starting before the db_recipes. Maybe your computer has low specs? 
You can try to edit the script that appears at the end of this [link](https://docs.docker.com/compose/startup-order/).

**Comment by vabene1111** [comment]
I think there is already a depends_on from web_recipes to db_recipes but as the docks say (and i guess you wanted to note @cesarblancg ) it does not wait until a container is ready but only until its started. So django might try to run the migrations before the database is up.

You could probably just start the containers after each user

`docker-compose up -d db_recipes` and after waiting a bit start web_recipes. As migrations only run on updates you would only need to do it then.

Usually the solution would be for me to implement some kind of healtcheck but to be honest the issue has never occured for anyone else so i dont see this as a big problem, at least as long as bigger ones exist 🤔 

also thanks @cesarblancg for pointing out the DB, i missed that

**Comment by cschoeni** [comment]
Thank you very much for your help. Is really gone on both because of. Both with the waiting file and with the start of the DB and then the web containers.

**Comment by vabene1111** [comment]
ok!. I have seen the PR, i guess it would help to have a wait for it script. 

I will close this issue and we will further discuss in the PR
