### ISSUE TITLE
Can't view or edit recipe

### ISSUE THREAD

**Issue by outdooracorn** [vabene1111/recipes#517]
### Version
Version: 0.14.5

### Bug description
I've run into the following error whilst adding my first recipe:
```
There was an error updating the recipe! <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html> 
```
Reloading the site or restarting the containers and trying to load or edit the recipe results in a similar error message and an infinite loading wheel.

Other things to note which might be useful:
- When creating the recipe I would click the "Save" button after creating each step (habit after losing text too many times due to an accidental page refresh)
- In the admin section I notice that there are multiple entries for items under `ingredients` and `steps`. I don't know if this is to be expected or not.
  <details>
  <summary>Screenshots</summary>

  ![image](https://user-images.githubusercontent.com/43674967/113447817-8785e580-93f2-11eb-9a4b-b345fcb8a721.png)
  ![image](https://user-images.githubusercontent.com/43674967/113448575-06c7e900-93f4-11eb-9f48-5c3ce567c55d.png)
  </summary>

The `docker-compose logs` didn't shed any light on the matter. Is there a way to enable/view more detailed logs to help debug this issue?

**Comment by outdooracorn** [comment]
<details>
<summary>Okay, I set `DEBUG=1` in the .env file and restarted and got this stacktrace when trying to view the recipe:</summary>

```
Environment:


Request Method: GET
Request URL: http://192.168.42.14/view/recipe/1

Django Version: 3.1.7
Python Version: 3.8.8
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_tables2',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (null value in column "space_id" violates not-null constraint
DETAIL:  Failing row contains (6, 2021-04-02 21:11:43.615367+00, 1, 1, null).
) was the direct cause of the following exception:
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/cookbook/views/views.py", line 181, in recipe_view
    ViewLog.objects.create(recipe=recipe, created_by=request.user)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /view/recipe/1
Exception Value: null value in column "space_id" violates not-null constraint
DETAIL:  Failing row contains (6, 2021-04-02 21:11:43.615367+00, 1, 1, null).
```
</details>

**Comment by outdooracorn** [comment]
I've fired up an [adminer](https://hub.docker.com/_/adminer) container to inspect the database to see if I could see where the `null` value in the `space_id` column was but I can't see any `null` values in any of the tables that have a `space_id` column.

<details>
<summary>I've also noticed that the first value in the "Failing row contains" tuple (on the last line) increments by one each time I refresh the page:</summary>

```
Environment:


Request Method: GET
Request URL: http://192.168.42.14/view/recipe/1

Django Version: 3.1.7
Python Version: 3.8.8
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_tables2',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (null value in column "space_id" violates not-null constraint
DETAIL:  Failing row contains (9, 2021-04-02 21:47:11.228891+00, 1, 1, null).
) was the direct cause of the following exception:
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/cookbook/views/views.py", line 181, in recipe_view
    ViewLog.objects.create(recipe=recipe, created_by=request.user)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /view/recipe/1
Exception Value: null value in column "space_id" violates not-null constraint
DETAIL:  Failing row contains (9, 2021-04-02 21:47:11.228891+00, 1, 1, null).
```
</details>

**Comment by outdooracorn** [comment]
<details>
<summary>Trying to get the recipe via the API (<code>http://192.168.42.14/api/recipe/1/</code>) raises a different error:</summary>

```
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/opt/recipes/cookbook/serializer.py", line 214, in get_ingredients_markdown
    return obj.get_instruction_render()
  File "/opt/recipes/cookbook/models.py", line 254, in get_instruction_render
    return render_instructions(self)
  File "/opt/recipes/cookbook/helper/template_helper.py", line 58, in render_instructions
    instructions = template.render(ingredients=ingredients)
  File "/opt/recipes/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/opt/recipes/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/opt/recipes/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
    <source code not available>
  File "/opt/recipes/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)

Exception Type: UndefinedError at /api/recipe/1/
Exception Value: list object has no element 0
```
</details>

I'll stop spamming you with emails now! Hopefully, some of this is useful.

As this is the first recipe I created I'm not too bothered about trying to fix this (i.e. don't spend too much time on this just for my sake). It could well be I messed something up with my config/setup. I'll leave it around for a couple of days in case you want me to help debug some more and then I'll probably blow it away and set it up afresh.

**Comment by vabene1111** [comment]
First of all thanks for the detailed report (no worries, i have email notfications turned off for issues :D)

Now you say that you are using 14.5 but the issue you describe is related to the spaces (multi tenant) feature of the next release. Are you sure you are running 14.5 and not the development version ?

Now the issue you describe might well relate to an issue in the code of the new version (i basically had to rewrite everything to make it multi tennant capable) but i do not have the issue on my instance, so there might be something database related

EDIT: While writing i noticed that parts of the spaces feature was already present in older versions. That leads to a few questions

1. Do you have any special/manual setup ? 
2. What database are you running ? 
3. In the admin view, is there a "space" in the spaces section ? There should be one default space which should have been automatically created in one of the previous versions using a migration

**Comment by outdooracorn** [comment]
Interesting! I am definitely currently running 14.5 but I may have accidentally run the development version when testing out other things. If this is the case I guess the problem is that I've accidentally upgraded the database schema to the development version and am now trying to run it with version 14.5 of the software.

1. I have changed the name of the services in the `docker-compose.yml` file and the login details to the database. I also had to manually change the Nginx config (`Recipes.conf`) in the `nginx_config` volume to match the new service name.
2. I'm using the default PostgreSQL database image as specified in the plain docker-compose setup
3. Yes, there is one space called "Default" 

I'll blow it all away and try again with the default setup nothing changed this time.

Out of curiosity, are there meant to be multiple entries for the same items under `ingredients` and `steps`? It would be useful to know if this is expected or not.

**Comment by outdooracorn** [comment]
Ahh okay, I think I found out what the issue was. I was trying to reference an ingredient (`{{ ingredients[0].food }}{# white onions #}`) that was in a different step (the step I was adding the reference to had no ingredients listed).

It might be useful to be able to link to ingredients from different steps. My use case here is that step 1 is "chop all ingredients" and then those ingredients are used in later steps. I guess linking across steps is challenging given how the database is structure (each step is its own entry in the `steps` table)? This is probably a discussion for another issue though.

Not a major issue, I can add it manually rather than trying to be clever and reference it now that I know what the issue is. Would be good to catch this error and provide a more informative error message though. :)

**Comment by vabene1111** [comment]
very interesting, thanks for the feedback 

1. Sadly "dead" entries in both spaces and ingredits tables are expected. This is because DRF does not delete them when they are unlinked to their parent object. This is something that will be fix in some later release and a migration will clean up the duplicates but i haven't gotten around to doing this.
2. linking trough steps would be cool but as you say very challenging. We will see in the future what can be done here
3. A broken link should not cause an issue when editing/saving a recipe. Does that work fine for you ? viewing would definitly be broken to some degree.

**Comment by vabene1111** [comment]
ok i just tested with my local setup: adding an {{ ingredients[5] }} tag to a step without ingredients does not cause any issues for me. It simply does not render (not even console errors which i fully expected). 

Can you export the recipe in question ? I am also very interested to see the results of the test with the default setup. Back porting the application after upgrading the database can btw definitely cause issues. Also the develop branch is very unstable at times.

**Comment by outdooracorn** [comment]
Haha, I was just writing a reply. I wonder if there is a difference between `{{ ingredients[5] }}` and `{{ ingredients[5].food }}`?

I just tried again and editing the recipe does cause an issue.
    <details>
    <summary>Here is a screen recording of it happening (sorry for the flicker):</summary>

    ![tandoor-error](https://user-images.githubusercontent.com/43674967/113503693-51984c80-952b-11eb-95d0-96d08e0fc50b.gif)
    </details>

   <details>
   <summary>I set DEBUG=1 and managed to inspect source to get this stacktrace:</summary>

    ```
    Environment: 
    
    Request Method: PUT 
    Request URL: http://192.168.42.14/api/recipe/1/ 
    
    Django Version: 3.1.7 
    Python Version: 3.8.8 
    Installed Applications: [
      'dal', 
      'dal_select2', 
      'django.contrib.admin', 
      'django.contrib.auth', 
      'django.contrib.contenttypes', 
      'django.contrib.sessions', 
      'django.contrib.messages', 
      'django.contrib.sites', 
      'django.contrib.staticfiles', 
      'django_tables2', 
      'django_filters', 
      'crispy_forms', 
      'emoji_picker', 
      'rest_framework', 
      'rest_framework.authtoken', 'django_cleanup.apps.CleanupConfig', 
      'webpack_loader', 
      'django_js_reverse', 
      'allauth', 
      'allauth.account', 
      'allauth.socialaccount', 
      'cookbook.apps.CookbookConfig'
    ] 
    
    Installed Middleware: [
      'django.middleware.security.SecurityMiddleware',
      'whitenoise.middleware.WhiteNoiseMiddleware',
      'django.contrib.sessions.middleware.SessionMiddleware',
      'django.middleware.common.CommonMiddleware',
      'django.middleware.csrf.CsrfViewMiddleware',
      'django.contrib.auth.middleware.AuthenticationMiddleware',
      'django.contrib.messages.middleware.MessageMiddleware',
      'django.middleware.locale.LocaleMiddleware',
      'django.middleware.clickjacking.XFrameOptionsMiddleware'
      ] 
      
      Traceback (most recent call last): 
        File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner 
          response = get_response(request) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response 
          response = wrapped_callback(request, *callback_args, **callback_kwargs) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view 
          return view_func(*args, **kwargs) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view 
          return self.dispatch(request, *args, **kwargs) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch 
          response = self.handle_exception(exc) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception 
          self.raise_uncaught_exception(exc) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception 
          raise exc 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch 
          response = handler(request, *args, **kwargs) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 75, in update 
          return Response(serializer.data) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data 
          ret = super().data 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data 
          self._data = self.to_representation(self.instance) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation 
          ret[field.field_name] = field.to_representation(attribute) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in 
          to_representation return [ 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp> 
          self.child.to_representation(item) for item in iterable 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation 
          ret[field.field_name] = field.to_representation(attribute) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 1870, in to_representation 
          return method(value) 
        File "/opt/recipes/cookbook/serializer.py", line 214, in get_ingredients_markdown 
          return obj.get_instruction_render() 
        File "/opt/recipes/cookbook/models.py", line 254, in get_instruction_render 
          return render_instructions(self) 
        File "/opt/recipes/cookbook/helper/template_helper.py", line 58, in render_instructions
          instructions = template.render(ingredients=ingredients) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render 
          self.environment.handle_exception() 
        File "/opt/recipes/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception 
          reraise(*rewrite_traceback_stack(source=source)) 
        File "/opt/recipes/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise  
          raise value.with_traceback(tb) 
        File "<template>", line 1, in top-level 
          template code <source code not available> 
        File "/opt/recipes/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr 
          return getattr(obj, attribute) 
        
        Exception Type: UndefinedError at /api/recipe/1/ 
        Exception Value: list object has no element 0 
    ```
   </details>

**Comment by vabene1111** [comment]
ah ok yes, i totally overlooked the .food in your example. This is the problem here. The reason is that markdown is rendered on the server (because i did not want to build both a python and a javascript markdown parser). 
It tries to render the template which causes an exception. 

I will get a fixed released with the next version

**Comment by vabene1111** [comment]
ok fixed with the next release. Recipes can be saved "broken" but will show a warning when rendered. 

This needs to be significantly improved in the future but for now its ok (the whole template feature is beta)
