### ISSUE TITLE
When using lvh.me, tandoor does not work

### ISSUE THREAD

**Issue by ModdedGamers** [vabene1111/recipes#570]
### Version
Version: 0.15.2
Ref: 625c04257e0822f32c8ddd646c9f08ed4fbbea8d

### Bug description
When using the `lvh.me` service, which just redirects all queries to localhost, tandoor gives a 500 error.

Log: 
```
Environment:


Request Method: GET
Request URL: http://recipes.lvh.me/accounts/login/?next=/search/

Django Version: 3.2
Python Version: 3.9.4
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'django_tables2',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 146, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 74, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 90, in get
    response = super(AjaxCapableProcessFormViewMixin, self).get(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 177, in get_context_data
    site = get_current_site(self.request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
    return Site.objects.get_current(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/models.py", line 58, in get_current
    return self._get_site_by_id(site_id)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /accounts/login/
Exception Value: Site matching query does not exist.
```

**Comment by ModdedGamers** [comment]
Here's the relevant part of my compose file:

```
  z_tandoor_db:
    image: postgres:11-alpine
    container_name: ztandoor_db
    restart: always
    volumes:
      - ./tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./tandoor/.env
    networks:
      recipes:
        ipv4_address: 172.0.2.2

  # Tandoor WebUI
  tandoor_webui:
    image: vabene1111/recipes
    container_name: tandoor_webui
    restart: always
    env_file:
      - ./tandoor/.env
    volumes:
      - tandoor_static:/opt/recipes/staticfiles
      - ./tandoor/nginx_config:/opt/recipes/nginx/conf.d
      - ./tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - z_tandoor_db
    networks:
      recipes:
        ipv4_address: 172.0.2.3

  # Tandoor Web Server
  z_tandoor_server:
    image: nginx:mainline-alpine
    container_name: ztandoor_server
    restart: always
    ports:
      - 9011:80
    env_file:
      - ./tandoor/.env
    depends_on:
      - tandoor_webui
    volumes:
      - ./tandoor/nginx_config:/etc/nginx/conf.d:ro
      - tandoor_static:/static
      - ./tandoor/mediafiles:/media
    networks:
      recipes:
        ipv4_address: 172.0.2.4
```

**Comment by ModdedGamers** [comment]
Here's my `.env` file:
DEBUG was set to 1 to get this backtrace, I normally have it set to 0.
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=1

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
SECRET_KEY=tRbHuNzW8jphVkAo+jz/Ev9fSab9mrf2YP5jt/GKoF4e3mxKcQ

# your default timezone See https://timezonedb.com/time-zones for a list of timezones
TIMEZONE=America/New_York

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
POSTGRES_HOST=172.0.2.2
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=password123
POSTGRES_DB=djangodb

# the default value for the user preference 'fractions' (enable/disable fraction support)
# default: disabled=0
FRACTION_PREF_DEFAULT=0

# the default value for the user preference 'comments' (enable/disable commenting system)
# default comments enabled=1
COMMENT_PREF_DEFAULT=1

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# Default for user setting sticky navbar
#STICKY_NAV_PREF_DEFAULT=1

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=./tandoor/static/

# If mediafiles are stored at a different location uncomment and change accordingly
MEDIA_URL=./tandoor/mediafiles/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# allow authentication via reverse proxy (e.g. authelia), leave off if you dont know what you are doing
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0


# allows you to setup OAuth providers
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# SOCIAL_PROVIDERS = allauth.socialaccount.providers.github, allauth.socialaccount.providers.nextcloud,
```

**Comment by smilerz** [comment]
@ModdedGamers does it work if you use http://127.0.0.1/ ?

Can you also share the nginx config

**Comment by ModdedGamers** [comment]
It does not work with 127.0.0.1. I use the proxy server [sozu](https://github.com/sozu-proxy/sozu). Here is my config for that:
```

log_level = "info"
log_target = "file:///Users/993390/compose/sozu/sozu.log"

worker_count = 1
worker_automatic_restart = true

max_connections = 50

max_buffers = 100

public_address = "127.0.0.1:80"

[[listeners]]

protocol = "http"
address = "0.0.0.0:80"

[applications.recipes]
protocol = "http"

frontends = [
  { address = "0.0.0.0:81", hostname = "recipes.lvh.me" }
]

backends = [
  { address = "127.0.0.1:9011"}
]

**Comment by smilerz** [comment]
can you take sozu out of the mix and try hitting http://recipes.lvh.me:9011/accounts/login

**Comment by ModdedGamers** [comment]
```
Environment:


Request Method: GET
Request URL: http://recipes.lvh.me:9011/accounts/login/

Django Version: 3.2
Python Version: 3.9.4
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'django_tables2',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 146, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 74, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 90, in get
    response = super(AjaxCapableProcessFormViewMixin, self).get(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 177, in get_context_data
    site = get_current_site(self.request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
    return Site.objects.get_current(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/models.py", line 58, in get_current
    return self._get_site_by_id(site_id)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /accounts/login/
Exception Value: Site matching query does not exist.
```

**Comment by vabene1111** [comment]
Have you verified that your application container is able to connect to the database ? Please look at the docker compose or whatever you have logs to see if there is any indication that the connection failed.

Thats at least what the model.DoesNotExists indicates. You could also log into your DB and see if tables were created

**Comment by ModdedGamers** [comment]
If i connect at `http://localhost:9011`, the connection to the app works.

**Comment by smilerz** [comment]
localhost works but 127.0.0.1 doesn't?  I'm totally baffled, this all works in my setup - did you change the nginx configuration at all?  are there local firewall rules?  I'm fairly certain there is anything in tandoor that is causing the issue.

**Comment by ModdedGamers** [comment]
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:9011/

Django Version: 3.2
Python Version: 3.9.4
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'django_tables2',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (relation "auth_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "auth_user"
                                          ^
) was the direct cause of the following exception:
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/cookbook/views/views.py", line 40, in index
    if User.objects.count() < 1 and 'django.contrib.auth.backends.RemoteUserBackend' not in settings.AUTHENTICATION_BACKENDS:
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 526, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 511, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /
Exception Value: relation "auth_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "auth_user"
                                          ^

```
when I try to connect to 127.0.0.1, this happens.

**Comment by smilerz** [comment]
None of that makes any sense.

The only thing I can think of is that there are two recipe apps running with 127.0.0.1 pointing at one without a db and localhost pointing to another with a db.  the SQL connections are backend and completely unaware of the web front end

**Comment by ModdedGamers** [comment]
I got it to reconnect to the db by resetting the password in the `.env` and through `psql`. I also set the nginx `server_name` to `0.0.0.0`, and it now connects to the db and logs me in. It still does not connect using 127.0.0.1.

**Comment by ModdedGamers** [comment]
When trtying to connect to 127.0.0.1:9011, this error shows up:
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:9011/accounts/login/?next=/search/

Django Version: 3.2
Python Version: 3.9.4
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'django_tables2',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 146, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 74, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 90, in get
    response = super(AjaxCapableProcessFormViewMixin, self).get(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/opt/recipes/venv/lib/python3.9/site-packages/allauth/account/views.py", line 177, in get_context_data
    site = get_current_site(self.request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
    return Site.objects.get_current(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/models.py", line 58, in get_current
    return self._get_site_by_id(site_id)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /accounts/login/
Exception Value: Site matching query does not exist.
```

**Comment by smilerz** [comment]
you still have a problem connecting to the db or running db migrations somewhere - what do the logs of the tandoor_webui container show?

**Comment by ModdedGamers** [comment]
![Screen Shot 2021-04-20 at 13 51 22](https://user-images.githubusercontent.com/35778371/115441995-84a33700-a1df-11eb-90b4-c1f373fc281d.png)

**Comment by ModdedGamers** [comment]
There's my log for the webui

**Comment by smilerz** [comment]
a handful of tests:
- can you try sudo nmap -v -p 5432 172.0.2.2
- does the postgres db have tables with data?
- what happens what you try to connect to 172.0.2.3:8080

**Comment by ModdedGamers** [comment]
Those IP's are mapped within the docker network. I wanted to make sure the bug was not with IPs getting mixed up.

**Comment by smilerz** [comment]
ok, change the ip addresses to 127.0.0.1 - same request though

**Comment by ModdedGamers** [comment]
in the docker compose, in the .env, or in the nginx config?

**Comment by smilerz** [comment]
this:

can you try sudo nmap -v -p 5432 127.0.0.1
does the postgres db have tables with data?
what happens what you try to connect to 127.0.0.1:8080

**Comment by ModdedGamers** [comment]
1. On my host, this returns a stopped psql service that I installed via `brew`.
2. There are tables with data in the db.
3. No connection is made, because I mapped 8080 to 9011.

**Comment by smilerz** [comment]
Where are you mapping 8080 to 9011?
 ```
 # Tandoor WebUI
  tandoor_webui:
    image: vabene1111/recipes
    container_name: tandoor_webui
    restart: always
    env_file:
      - ./tandoor/.env
    volumes:
      - tandoor_static:/opt/recipes/staticfiles
      - ./tandoor/nginx_config:/opt/recipes/nginx/conf.d
      - ./tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - z_tandoor_db
    networks:
      recipes:
        ipv4_address: 172.0.2.3
```

**Comment by ModdedGamers** [comment]
```
ztandoor_server:
    image: nginx:mainline-alpine
    container_name: ztandoor_server
    restart: always
    ports:
      - 9011:80
    env_file:
      - ./tandoor/.env
    depends_on:
      - tandoor_webui
    volumes:
      - ./tandoor/nginx_config:/etc/nginx/conf.d:ro
      - tandoor_static:/static
      - ./tandoor/mediafiles:/media
    networks:
      recipes:
        ipv4_address: 172.0.2.4
```

**Comment by ModdedGamers** [comment]
in the nginx block, it redirects nginx's port 80 to 9011 on the host.

**Comment by smilerz** [comment]
niginx is seperate from django - django is listening on 8080

**Comment by ModdedGamers** [comment]
when doing that, lvh.me:8080 and 127.0.0.1:8080 both get a 500 server error, and localhost:8080 works as usual.

**Comment by smilerz** [comment]
unless localhost is routing someplace else, I'm at a loss.  the hostname isn't going to change the behavior of the database.

**Comment by vabene1111** [comment]
I am sorry, your setup is so far away from what i would call "standard" that i really cannot justify spending time debugging it further. Also i have never used lvh.me and the other services you describe so no idea about it

If the database connects and the local connection trough the port directly is working without problems than your problem probably lies in your proxy/lvh setup. Here you might have problems because of missing headers or wrong redirects. 

If you have stakcktrace or real error messages that are shown anywhere (during container startup or when browsing an url) feel free to post them and i can tell you what they mean but other than that you will need to make sure that the requets makes it trough to the application the same way it would without the reverse proxies. The 500 error in the browser is usually also accompanied by a stack trace somewhere in your container stack
