### ISSUE TITLE
Invalid Syntax error on initial install

### ISSUE THREAD

**Issue by qgiguiere** [vabene1111/recipes#68]
I am trying to do a manual install on Debian 10. I downloaded the latest release and installed all the dependencies in requirements.txt. I am also following the linked guide to set up a django app with nginx. However, when I try to run `python manage.py runserver 0.0.0.0:8000`, I get errors that I can't figure out how to resolve. The full error message I am getting is the following:
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fc127ef5620>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.7/dist-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.7/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<PATH>/recipes-0.7.0/cookbook/models.py", line 11
    if not (name := f"{self.first_name} {self.last_name}") == " ":
                 ^
SyntaxError: invalid syntax
```

**Comment by vabene1111** [comment]
do you have python version 3.8 or higher installed ? 

The syntax you are referring to is because i use the python 3.8 walrus operator thus you have to install it (sry, but i am kind of a always update/use the latest stuff guy, obviously a little annoying for manual installs but since most people use docker i didn't mind)

**Comment by qgiguiere** [comment]
I do not, I only have the default 3.7. I will install 3.8 and try again, thank you!

**Comment by vabene1111** [comment]
perfect, just close this please when it resolves the issue. If not feel free to ask again and i will take a closer look
