### ISSUE TITLE
Relation "cookbook_space" does not exist

### ISSUE THREAD

**Issue by es737** [vabene1111/recipes#688]
Docker - latest as well as 0.16.1, 0.15.2, and 0.14.5

After docker container is launched, I enter IP address in browser and I am redirected to /setup/ where I get exception message:

ProgrammingError at /setup/
relation "cookbook_space" does not exist
LINE 1: ...ok_space"."name", "cookbook_space"."message" FROM "cookbook_...
                                                             ^
Request Method:	GET
Request URL:	http://192.168.100.13:81/setup/
Django Version:	3.1.7
Exception Type:	ProgrammingError
Exception Value:	
relation "cookbook_space" does not exist
LINE 1: ...ok_space"."name", "cookbook_space"."message" FROM "cookbook_...
                                                             ^
Exception Location:	/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py, line 84, in _execute
Python Executable:	/opt/recipes/venv/bin/python
Python Version:	3.8.8
Python Path:	
['/opt/recipes',
 '/opt/recipes/venv/bin',
 '/usr/local/lib/python38.zip',
 '/usr/local/lib/python3.8',
 '/usr/local/lib/python3.8/lib-dynload',
 '/opt/recipes/venv/lib/python3.8/site-packages']
Server time:	Fri, 11 Jun 2021 03:14:42 +0200

Environment:

Request Method: GET
Request URL: http://192.168.100.13:81/setup/

Django Version: 3.1.7
Python Version: 3.8.8
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_tables2',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template error:
In template /opt/recipes/cookbook/templates/base.html, error at line 173
   relation "cookbook_space" does not exist
LINE 1: ...ok_space"."name", "cookbook_space"."message" FROM "cookbook_...
                                                             ^

   163 :                 </li>
   164 :             {% else %}
   165 :                 <li class="nav-item">
   166 :                     <a class="nav-link" href="{% url 'account_logout' %}">{% trans 'Login' %} <i class="fas fa-sign-in-alt"></i></a>
   167 :                 </li>
   168 :             {% endif %}
   169 :         </ul>
   170 :     </div>
   171 : </nav>
   172 : 
   173 :  {% message_of_the_day as message_of_the_day %} 
   174 : {% if message_of_the_day %}
   175 :     <div class="bg-warning" style=" width: 100%; text-align: center!important; color: #ffffff; padding: 8px">
   176 :         {{ message_of_the_day }}
   177 :     </div>
   178 : {% endif %}
   179 : 
   180 : <br/>
   181 : <br/>
   182 : 
   183 : <div class="container-fluid" id="id_base_container">

Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (relation "cookbook_space" does not exist
LINE 1: ...ok_space"."name", "cookbook_space"."message" FROM "cookbook_...
                                                             ^
) was the direct cause of the following exception:
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/cookbook/views/views.py", line 411, in setup
    return render(request, 'setup.html', {'form': form})
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/opt/recipes/cookbook/templatetags/custom_tags.py", line 103, in message_of_the_day
    return Space.objects.first().message
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 678, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /setup/
Exception Value: relation "cookbook_space" does not exist
LINE 1: ...ok_space"."name", "cookbook_space"."message" FROM "cookbook_...
                                                             ^

**Comment by vabene1111** [comment]
can you post the outputs of docker-compose logs (or equivalent) at container startup ? the issue indicates that the application is not able to make a database query which might mean that the database server is offline or that the migrations could not be applied (maybe missing permissions)

**Comment by smilerz** [comment]
I ran into this too. I think a migration got set out of order.  I had to create a custom migration to fix it

**Comment by es737** [comment]
Looks like permission issue. Should have looked at docker logs.

Updating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
Running migrations:
  Applying cookbook.0003_enable_pgtrm...Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: permission denied to create extension "pg_trgm"
HINT:  Must be superuser to create this extension.

**Comment by es737** [comment]
Is superuser required for the initial run or is it always required to run the app? I grant all privileges to service account for the recipes database and looks like it wasn't enough. I'm not terribly familiar with postgresql.

**Comment by vabene1111** [comment]
the user being the owner of the databse should suffice, i recently setup a postgres environment with a simple user that was only owner of the tandoor database so i think no global superuser is required. But yes that permission is needed to activate the extensions required for the search

**Comment by es737** [comment]
May I suggest updating instructions to indicate the user one creates for the new recipes database needs to have superuser role and after the initial run of the docker container, one can remove the superuser role. This is what I did and it worked for me. Of course, at some point in the future, I may need to grant superuser role to the user if the app has database changes.

**Comment by vabene1111** [comment]
yes that makes sense 👍
