### ISSUE TITLE
AllRecipes import fails "Max retries exceeded"

### ISSUE THREAD

**Issue by Arsoth** [vabene1111/recipes#694]
### Version
Version: 0.16.2

### Bug description
When attempting to import from AllRecipes a 500 internal server error occurs on Tandoor. Checking Docker logs it looks like the issue is with images failing to import and crashing out:

```
172.18.0.4 - - [12/Jun/2021:16:29:34 -0400] "POST /api/recipe-from-source/ HTTP/1.0" 200 3571 "http://192.168.86.86/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"

3 tablespoons olive oil

1 large onion

1 bunch green onions

2 cloves garlic

2 pounds spinach

0.5 cup chopped fresh parsley

2 None eggs

0.5 cup ricotta cheese

cup crumbled feta cheese

8 sheets phyllo dough

0.25 cup olive oil

ERROR:django.request:Internal Server Error: /data/import/url

Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn

    conn = connection.create_connection(

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection

    raise err

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection

    sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen

    httplib_response = self._make_request(

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request

    self._validate_conn(conn)

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn

    conn.connect()

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect

    conn = self._new_conn()

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn

    raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x737553e8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen

    retries = retries.increment(

  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='imagesvc.meredithcorp.io', port=443): Max retries exceeded with url: /v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F754051.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x737553e8>: Failed to establish a new connection: [Errno 111] Connection refused'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner

    response = get_response(request)

  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view

    return view_func(request, *args, **kwargs)

  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner

    return func(*args, **kwds)

  File "/opt/recipes/cookbook/views/data.py", line 188, in import_url

    response = requests.get(data['image'])

  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/api.py", line 76, in get

    return request('get', url, params=params, **kwargs)

  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request

    return session.request(method=method, url=url, **kwargs)

  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/adapters.py", line 516, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='imagesvc.meredithcorp.io', port=443): Max retries exceeded with url: /v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F754051.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x737553e8>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I assume that allowing image imports to fail if the rest of the recipe worked would probably be a viable workaround; the total import on my end works, but pressing the import button is what fails, so the important bits make it, they just can't be saved.

**Comment by vabene1111** [comment]
interesting, we had some image problems in the past so i thought we added appropriate error catching there .. i will take a look
