### ISSUE TITLE
error 500 on recipe creation

### ISSUE THREAD

**Issue by sqozz** [vabene1111/recipes#723]
### Version
Version: master as well as 0.16.7 where tried

### Bug description
When creating a new recipe the backend produces an error 500 and shows the error:

```
There was an error loading the recipe! <!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html> 
```

The server logs show the following:
*EDIT:* changed to debug it shows:
```
/opt/tandoor/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Recipe.created_at received a naive datetime (2021-06-13 18:10:52.025371) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
Internal Server Error: /api/recipe/6/
Traceback (most recent call last):
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFunction: function similarity(character varying, unknown) does not exist
LINE 1: ...:timestamptz THEN 100 ELSE 0 END AS "new_recipe", SIMILARITY...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/tandoor/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/opt/tandoor/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/tandoor/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: function similarity(character varying, unknown) does not exist
LINE 1: ...:timestamptz THEN 100 ELSE 0 END AS "new_recipe", SIMILARITY...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

### Setup notes
I followed https://docs.tandoor.dev/install/manual.html to create my setup. I also executed the additional steps described in the "Setup postgresql" section. I use the following command for debugging as user "tandoor" to run the application:

```
gunicorn --log-level debug --capture-output --bind unix:/run/tandoor/tandoor.sock recipes.wsgi:application
```

**Comment by vabene1111** [comment]
Debugging the manual setup is always a little tricky.

Can you set DEBUG=1 in your environment as it will make gunicorn produce more detailed logs


There might also be some messages in the browser console, if you know how to read it you can look if there is a message after the 500 error

**Comment by sqozz** [comment]
Seems this is 100% my screw up. I tried to be super smart and created the needed extensions with the wrong user. Now with `pg_trgm` and `unaccent` properly enabled everything works as intended. Sorry for the noise and thanks for your fast feedback!

**Comment by vabene1111** [comment]
No worried, glad you figured it out. Feel free to let me know if you have any further issues or ideas
