### ISSUE TITLE
Docker container is missing dependencies

### ISSUE THREAD

**Issue by djmixman** [vabene1111/recipes#805]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: docker latest

### Bug description
Unable to find files when trying to setup the database. Using an external postgres server.

`docker exec -it Tandoor-backend sh`
```
/opt/recipes # cd /usr/local/share/
/usr/local/share # ls -l
total 1
drwxr-xr-x    2 root     root             2 Apr 14 23:33 ca-certificates
drwxr-xr-x    3 root     root             3 May  4 13:43 man
```

No postgres directory is found.

```text
Tandoor-backend     | The above exception was the direct cause of the following exception:
Tandoor-backend     |
Tandoor-backend     | Traceback (most recent call last):
Tandoor-backend     |   File "/opt/recipes/manage.py", line 15, in <module>
Tandoor-backend     |     execute_from_command_line(sys.argv)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
Tandoor-backend     |     utility.execute()
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
Tandoor-backend     |     self.fetch_command(subcommand).run_from_argv(self.argv)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
Tandoor-backend     |     self.execute(*args, **cmd_options)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
Tandoor-backend     |     output = self.handle(*args, **options)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
Tandoor-backend     |     res = handle_func(*args, **kwargs)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
Tandoor-backend     |     post_migrate_state = executor.migrate(
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
Tandoor-backend     |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
Tandoor-backend     |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
Tandoor-backend     |     state = migration.apply(state, schema_editor)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
Tandoor-backend     |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/postgres/operations.py", line 25, in database_forwards
Tandoor-backend     |     schema_editor.execute(
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute
Tandoor-backend     |     cursor.execute(sql, params)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
Tandoor-backend     |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
Tandoor-backend     |     return executor(sql, params, many, context)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
Tandoor-backend     |     return self.cursor.execute(sql, params)
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
Tandoor-backend     |     raise dj_exc_value.with_traceback(traceback) from exc_value
Tandoor-backend     |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
Tandoor-backend     |     return self.cursor.execute(sql, params)
Tandoor-backend     | django.db.utils.OperationalError: could not open extension control file "/usr/local/share/postgresql/extension/pg_trgm.control": No such file or directory
```

```docker-compose
---
version: "3"
services:
  Tandoor-backend:
    image: vabene1111/recipes
    container_name: Tandoor-backend
    env_file:
      - configs/common.defaults.env
      - configs/config.Tandoor.env
    networks:
      - Tandoor
    volumes:
      - Tandoor_staticfiles:/opt/recipes/staticfiles
      - Tandoor_nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    restart: unless-stopped

  Tandoor-frontend:
    image: nginx:mainline-alpine
    restart: unless-stopped
    container_name: Tandoor-frontend
    networks:
      - Tandoor
    ports:
      - 51037:80
    env_file:
      - configs/common.defaults.env
      - configs/config.Tandoor.env
    depends_on:
      - Tandoor-backend
    volumes:
      - Tandoor_nginx_config:/etc/nginx/conf.d:ro
      - Tandoor_staticfiles:/static
      - ./mediafiles:/media

volumes:
  Tandoor_nginx_config:
  Tandoor_staticfiles:
  
networks:
  Tandoor:
````

**Comment by vabene1111** [comment]
your database is missing an extension pg_trm, since you appear to not be running the database as part of the compose stack you might need to manually install it into your database server

**Comment by djmixman** [comment]
@vabene1111 Looks like that was the issue. Thanks for the pointer, I'm a bit new to Postgres.

**Comment by vabene1111** [comment]
no worries, glad it works now 👍
