### ISSUE TITLE
Any export fails with "sqlite3.IntegrityError: NOT NULL constraint failed: cookbook_keyword.depth"

### ISSUE THREAD

**Issue by raleeper** [vabene1111/recipes#841]
### Version
This is in the development branch. Version number reports as 0.0.0

### Bug description
I was using the Default export format, but I don't think it matters. Running the _export_ tries to create a keyword describing an _import_ and the keyword creation fails for a sqlite database with "sqlite3.IntegrityError: NOT NULL constraint failed: cookbook_keyword.depth". If the export had worked it looks like it would have stored an un-referenced keyword in the database.

I am not sure having an import create a keyword is good behavior either, but that's probably a separate issue.

### Traceback
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/export/

Django Version: 3.2.6
Python Version: 3.9.6
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'django_prometheus',
 'django_tables2',
 'corsheaders',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'hcaptcha',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig',
 'treebeard']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (NOT NULL constraint failed: cookbook_keyword.depth) was the direct cause of the following exception:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/workspace/cookbook/views/import_export.py", line 112, in export_recipe
    integration = get_integration(request, form.cleaned_data['type'])
  File "/workspace/cookbook/views/import_export.py", line 33, in get_integration
    return Default(request, export_type)
  File "/workspace/cookbook/integration/integration.py", line 49, in __init__
    self.keyword = Keyword.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.9/site-packages/django_prometheus/models.py", line 43, in _do_insert
    return super()._do_insert(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: IntegrityError at /export/
Exception Value: NOT NULL constraint failed: cookbook_keyword.depth
```

**Comment by vabene1111** [comment]
thank you for reporting. The development branch tends to be a little unstable but its good that you help test it.

@smilerz i guess this is related to the keywords tree. I had several issues with the importer in older versions, maybe we should add a unit test for exporting and then importing a backup.

In general i am not a big fan of the current exporter, its nice for recipes but it still looses some data, i will need to find a better way to generate complete instance exports

**Comment by smilerz** [comment]
I'm trying to finish up a Foods change, so not sure when I'll be able to fix it and write a test.  But the 2nd part of this IF statement in integration.py needs to be switched to get_or_create.

```

        if DATABASES['default']['ENGINE'] in ['django.db.backends.postgresql_psycopg2', 'django.db.backends.postgresql']:
            parent, created = Keyword.objects.get_or_create(name='Import', space=request.space)
            self.keyword = parent.add_child(
                name=name,
                description=description,
                icon=icon,
                space=request.space
            )
        else:
            self.keyword = Keyword.objects.create(
                name=name,
                description=description,
                icon=icon,
                space=request.space
            )

```

**Comment by vabene1111** [comment]
i can look into this as well, no worries

**Comment by vabene1111** [comment]
thanks @smilerz for pointing out the right placed, fixed this and some other issues so import should work again. need to do a proper test of all importer types later
